### List all messages
GET http://localhost:3000/messages


### Create new message
POST http://localhost:3000/messages
content-type: application/json

{
    "content": "Tercer mensaje prueba. Luego de DI"
}


### Get particular message
GET http://localhost:3000/messages/195
